[server]
headless = true
enableXsrfProtection = true
port = 8501

[theme]
base = "dark"
primaryColor = "#00ADB5"
backgroundColor = "#222831"
secondaryBackgroundColor = "#393E46"
textColor = "#EEEEEE"
font = "sans serif"